/**
 * Build step for the animated homepage hero.
 *
 * Transpiles the JSX engine + scene (authored in
 * public/assets/heroe section/) into plain browser JS under
 * public/assets/hero/. Only JSX is transformed — modern syntax
 * (const/arrow/optional-chaining) is left as-is for evergreen browsers.
 *
 * Run after editing the .jsx sources:   node scripts/build-hero.js
 */
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const SRC = path.join(__dirname, '..', 'public', 'assets', 'heroe section');
const OUT = path.join(__dirname, '..', 'public', 'assets', 'hero');

const FILES = [
  ['animations.jsx', 'animations.js'],
  ['crevia-scenes.jsx', 'crevia-scenes.js'],
];

fs.mkdirSync(OUT, { recursive: true });

for (const [from, to] of FILES) {
  const code = fs.readFileSync(path.join(SRC, from), 'utf8');
  const { code: out } = babel.transformSync(code, {
    filename: from,
    presets: [['@babel/preset-react', { runtime: 'classic', pragma: 'React.createElement' }]],
    compact: false,
    comments: false,
  });
  const banner = `// GENERATED by scripts/build-hero.js from "${from}" — do not edit directly.\n`;
  // Wrap in an IIFE: the files are loaded as separate classic <script>s, which
  // share one global lexical scope — without this, top-level `const Sprite`,
  // `const Easing`, etc. collide across files ("already been declared"). The
  // engine exports via window.* / Object.assign(window,...), which still work.
  const wrapped = banner + ';(function () {\n' + out + '\n})();\n';
  fs.writeFileSync(path.join(OUT, to), wrapped, 'utf8');
  console.log(`✓ ${from} -> assets/hero/${to} (${out.length} bytes)`);
}
console.log('Hero build complete.');
